services:
  - type: web
    name: ruta-de-las-palabras-4a
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
